// promise.then(function(result){handle}
// function(error){handle error}
// )

// .then() takes 2 arguments first result and second errors if we are only interested in handling errors then we can give the 1st argument as null and then comma and then function for handling error if we want to catch error using .then() instead of .catch() or we can use .catch() for handling errors we can use both options for errors. 

